/**
 * Barcode Standards & Format Definitions for Rootixa QR & Barcode Studio
 * Production-ready specifications for retail, business, logistics, packaging, and GS1.
 */

export const BARCODE_CATEGORIES = [
  { id: "all", label: "All Standards (9)" },
  { id: "retail", label: "Retail & Consumer" },
  { id: "general", label: "General & Industrial" },
  { id: "logistics", label: "Logistics & Packaging" },
  { id: "gs1", label: "Professional / GS1" },
  { id: "specialized", label: "Specialized" },
];

export const BARCODE_FORMATS = [
  // 1. General & Industrial
  {
    id: "CODE128",
    name: "Code 128",
    subtitle: "High-density alphanumeric standard",
    category: "General & Industrial",
    categoryId: "general",
    description:
      "High-density alphanumeric barcode supporting all 128 standard ASCII characters. Widely used for shipping labels, asset management, and internal inventory tracking.",
    inputRequirements: "Standard ASCII characters (letters, numbers, basic punctuation).",
    allowedCharset: "ASCII 0–127 (letters, digits, symbols)",
    defaultData: "ROOTIXA-128-PRO",
    example: "ROOTIXA-128-PRO",
    placeholder: "e.g. ROOTIXA-128-PRO or INV-89421",
    helper: "Accepts uppercase and lowercase letters, numbers, and standard punctuation.",
    hasCheckDigit: true,
    supportsAutoCheckDigit: false, // Handled automatically by the Code 128 encoder
    minChars: 1,
    maxChars: 80,
    jsbarcodeFormat: "CODE128",
  },
  {
    id: "CODE39",
    name: "Code 39",
    subtitle: "Industrial & defense barcode standard",
    category: "General & Industrial",
    categoryId: "general",
    description:
      "Self-checking alphanumeric standard widely used in aerospace, defense, automotive, and healthcare equipment tracking.",
    inputRequirements: "Uppercase letters (A-Z), digits (0-9), and symbols (- . $ / + % space).",
    allowedCharset: "0–9, A–Z, -, ., $, /, +, %, space",
    defaultData: "ROOTIXA39",
    example: "PART-9821-X",
    placeholder: "e.g. PART-9821-X",
    helper: "Lowercase characters are automatically converted to uppercase.",
    hasCheckDigit: false,
    supportsAutoCheckDigit: false,
    minChars: 1,
    maxChars: 43,
    jsbarcodeFormat: "CODE39",
  },

  // 2. Retail & Consumer
  {
    id: "EAN13",
    name: "EAN-13",
    subtitle: "Global retail product barcode",
    category: "Retail & Consumer",
    categoryId: "retail",
    description:
      "International standard for consumer products scanned at retail points of sale worldwide. Encodes 12 product digits plus 1 Modulo 10 check digit.",
    inputRequirements: "12 data digits (auto check digit) or full 13 numeric digits.",
    allowedCharset: "Numeric digits only (0–9)",
    defaultData: "590123412345",
    example: "5901234123457",
    placeholder: "Enter 12 or 13 digits (e.g. 590123412345)",
    helper: "Enter 12 digits to calculate checksum automatically, or enter all 13 digits.",
    hasCheckDigit: true,
    supportsAutoCheckDigit: true,
    baseLength: 12,
    totalLength: 13,
    numericOnly: true,
    jsbarcodeFormat: "EAN13",
  },
  {
    id: "EAN8",
    name: "EAN-8",
    subtitle: "Compact retail barcode for small items",
    category: "Retail & Consumer",
    categoryId: "retail",
    description:
      "Compact European Article Number designed specifically for small packages and cosmetics where an EAN-13 barcode is too large to fit.",
    inputRequirements: "7 data digits (auto check digit) or full 8 numeric digits.",
    allowedCharset: "Numeric digits only (0–9)",
    defaultData: "9638507",
    example: "96385074",
    placeholder: "Enter 7 or 8 digits (e.g. 9638507)",
    helper: "Enter 7 digits to calculate checksum automatically, or enter all 8 digits.",
    hasCheckDigit: true,
    supportsAutoCheckDigit: true,
    baseLength: 7,
    totalLength: 8,
    numericOnly: true,
    jsbarcodeFormat: "EAN8",
  },
  {
    id: "UPC",
    name: "UPC-A",
    subtitle: "North American point-of-sale barcode",
    category: "Retail & Consumer",
    categoryId: "retail",
    description:
      "Standard retail point-of-sale barcode in the United States and Canada. Encodes 11 data digits plus 1 Modulo 10 check digit.",
    inputRequirements: "11 data digits (auto check digit) or full 12 numeric digits.",
    allowedCharset: "Numeric digits only (0–9)",
    defaultData: "01234567890",
    example: "012345678905",
    placeholder: "Enter 11 or 12 digits (e.g. 01234567890)",
    helper: "Enter 11 digits to calculate checksum automatically, or enter all 12 digits.",
    hasCheckDigit: true,
    supportsAutoCheckDigit: true,
    baseLength: 11,
    totalLength: 12,
    numericOnly: true,
    jsbarcodeFormat: "UPC",
  },
  {
    id: "UPCE",
    name: "UPC-E",
    subtitle: "Zero-suppressed compact UPC barcode",
    category: "Retail & Consumer",
    categoryId: "retail",
    description:
      "Zero-suppressed compact version of UPC-A for small retail items in North America. Expands to a full 12-digit UPC-A for checksum calculation.",
    inputRequirements: "6 compressed digits or 8 digits (number system 0/1 + 6 digits + check digit).",
    allowedCharset: "Numeric digits only (0–9)",
    defaultData: "01234505",
    example: "01234505",
    placeholder: "e.g. 012345 or 01234505",
    helper: "Enter 6 compressed digits or full 8 digits starting with 0 or 1.",
    hasCheckDigit: true,
    supportsAutoCheckDigit: true,
    baseLength: 6,
    totalLength: 8,
    numericOnly: true,
    jsbarcodeFormat: "UPCE",
  },

  // 3. Logistics & Packaging
  {
    id: "ITF14",
    name: "ITF-14",
    subtitle: "Logistics master carton & case barcode",
    category: "Logistics & Packaging",
    categoryId: "logistics",
    description:
      "Interleaved 2 of 5 standard used on corrugated cardboard cartons, master cases, and bulk shipping containers in supply chains.",
    inputRequirements: "13 data digits (auto check digit) or full 14 numeric digits.",
    allowedCharset: "Numeric digits only (0–9)",
    defaultData: "1001234567890",
    example: "10012345678902",
    placeholder: "Enter 13 or 14 digits (e.g. 1001234567890)",
    helper: "Enter 13 digits to calculate checksum automatically, or enter all 14 digits.",
    hasCheckDigit: true,
    supportsAutoCheckDigit: true,
    baseLength: 13,
    totalLength: 14,
    numericOnly: true,
    jsbarcodeFormat: "ITF14",
  },

  // 4. Specialized
  {
    id: "codabar",
    name: "Codabar",
    subtitle: "Numeric standard for blood banks & libraries",
    category: "Specialized",
    categoryId: "specialized",
    description:
      "Self-checking discrete symbology used in medical blood banks, libraries, parcel delivery manifests, and lab specimen tubes.",
    inputRequirements: "Digits 0–9 and symbols (- $ : / . +) with optional framing letters A, B, C, D.",
    allowedCharset: "0–9, -, $, :, /, ., +, and start/stop letters A, B, C, D",
    defaultData: "A123456789B",
    example: "A9876543210B",
    placeholder: "e.g. A123456789B",
    helper: "Use start/stop framing characters A, B, C, or D at the beginning and end.",
    hasCheckDigit: false,
    supportsAutoCheckDigit: false,
    minChars: 2,
    maxChars: 32,
    jsbarcodeFormat: "codabar",
  },

  // 5. Professional / GS1
  {
    id: "GS1_128",
    name: "GS1-128",
    subtitle: "Global supply chain & logistics standard",
    category: "Professional / GS1",
    categoryId: "gs1",
    description:
      "International standard encoding data with Application Identifiers (AIs) like GTIN (01), Batch/Lot (10), Expiration Date (17), and Serial Number (21).",
    inputRequirements: "Parenthesized Application Identifiers, e.g. (01)01234567890128(17)261231(10)LOT123",
    allowedCharset: "Application Identifiers in () followed by valid alphanumeric values",
    defaultData: "(01)01234567890128(17)261231(10)LOT982",
    example: "(01)01234567890128(17)261231(10)LOT982",
    placeholder: "e.g. (01)01234567890128(17)261231(10)BATCH123",
    helper: "Use standard (AI) format like (01) for GTIN, (10) for Lot, (17) for Expiry, (21) for Serial.",
    hasCheckDigit: true,
    supportsAutoCheckDigit: false,
    isGs1: true,
    jsbarcodeFormat: "CODE128",
  },
];

export const BARCODE_PRESETS = [
  {
    id: "classic",
    name: "Classic",
    description: "Standard clean black & white with balanced proportions",
    badge: "General Purpose",
    settings: {
      lineColor: "#000000",
      background: "#FFFFFF",
      isTransparentBg: false,
      width: 2,
      height: 80,
      margin: 15,
      displayValue: true,
      textPosition: "bottom",
      fontSize: 14,
      fontOptions: "bold",
      textAlign: "center",
      textMargin: 3,
    },
  },
  {
    id: "retail",
    name: "Retail POS",
    description: "High-contrast compact layout optimized for checkout scanners",
    badge: "Retail & Packaging",
    settings: {
      lineColor: "#000000",
      background: "#FFFFFF",
      isTransparentBg: false,
      width: 2,
      height: 65,
      margin: 12,
      displayValue: true,
      textPosition: "bottom",
      fontSize: 13,
      fontOptions: "bold",
      textAlign: "center",
      textMargin: 2,
    },
  },
  {
    id: "business",
    name: "Business & Logistics",
    description: "Tall industrial bars with generous quiet zone for distance scanning",
    badge: "Warehousing",
    settings: {
      lineColor: "#0F172A",
      background: "#FFFFFF",
      isTransparentBg: false,
      width: 2.4,
      height: 110,
      margin: 24,
      displayValue: true,
      textPosition: "bottom",
      fontSize: 15,
      fontOptions: "bold",
      textAlign: "center",
      textMargin: 4,
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Modern slim module width with refined quiet zone",
    badge: "Modern Clean",
    settings: {
      lineColor: "#1E293B",
      background: "#FFFFFF",
      isTransparentBg: false,
      width: 1.6,
      height: 70,
      margin: 16,
      displayValue: true,
      textPosition: "bottom",
      fontSize: 13,
      fontOptions: "",
      textAlign: "center",
      textMargin: 3,
    },
  },
  {
    id: "compact",
    name: "Compact Label",
    description: "Low-profile layout for small shelf tags and narrow packaging",
    badge: "Shelf & Tags",
    settings: {
      lineColor: "#000000",
      background: "#FFFFFF",
      isTransparentBg: false,
      width: 1.8,
      height: 50,
      margin: 10,
      displayValue: true,
      textPosition: "bottom",
      fontSize: 12,
      fontOptions: "bold",
      textAlign: "center",
      textMargin: 2,
    },
  },
];
