/**
 * Barcode Standards & Format Definitions for Rootixa QR & Barcode Studio
 */

export const BARCODE_FORMATS = [
  {
    id: "CODE128",
    name: "Code 128",
    subtitle: "General-purpose barcode",
    category: "General & Industrial",
    description: "High-density alphanumeric barcode supporting all 128 standard ASCII characters. Ideal for shipping, inventory, and asset tracking.",
    defaultData: "ROOTIXA-128-PRO",
    placeholder: "Enter letters, numbers, or standard ASCII",
    helper: "Enter numbers, letters, or supported ASCII characters.",
    hasCheckDigit: true,
    supportsAutoCheckDigit: false, // Code 128 check digit is handled automatically by the encoder internally
    minChars: 1,
    maxChars: 80,
  },
  {
    id: "CODE39",
    name: "Code 39",
    subtitle: "Alphanumeric industrial barcode",
    category: "Industrial & Defense",
    description: "Widely used standard in defense, automotive, and healthcare. Supports uppercase letters (A-Z), digits (0-9), and basic punctuation (- . $ / + % space).",
    defaultData: "ROOTIXA39",
    placeholder: "e.g. PART-9821-X",
    helper: "Enter uppercase letters, numbers, and symbols (- . $ / + % space).",
    hasCheckDigit: false,
    supportsAutoCheckDigit: false,
    minChars: 1,
    maxChars: 43,
  },
  {
    id: "EAN13",
    name: "EAN-13",
    subtitle: "Retail product barcode",
    category: "Retail & Consumer",
    description: "International standard for consumer goods sold at retail point-of-sale worldwide. Uses 12 data digits plus 1 Modulo 10 check digit.",
    defaultData: "590123412345",
    placeholder: "Enter 12 or 13 digits (e.g. 590123412345)",
    helper: "Enter 12 or 13 digits.",
    hasCheckDigit: true,
    supportsAutoCheckDigit: true,
    baseLength: 12,
    totalLength: 13,
    numericOnly: true,
  },
  {
    id: "EAN8",
    name: "EAN-8",
    subtitle: "Compact retail barcode",
    category: "Retail & Consumer",
    description: "Compact European Article Number for small items and packaging where standard EAN-13 is too large. Uses 7 data digits plus 1 check digit.",
    defaultData: "9638507",
    placeholder: "Enter 7 or 8 digits (e.g. 9638507)",
    helper: "Enter 7 or 8 digits.",
    hasCheckDigit: true,
    supportsAutoCheckDigit: true,
    baseLength: 7,
    totalLength: 8,
    numericOnly: true,
  },
  {
    id: "UPC",
    name: "UPC-A",
    subtitle: "North American retail barcode",
    category: "Retail & Consumer",
    description: "The primary retail barcode standard in the United States and Canada. Encodes 11 data digits plus 1 Modulo 10 check digit.",
    defaultData: "01234567890",
    placeholder: "Enter 11 or 12 digits (e.g. 01234567890)",
    helper: "Enter 11 or 12 digits.",
    hasCheckDigit: true,
    supportsAutoCheckDigit: true,
    baseLength: 11,
    totalLength: 12,
    numericOnly: true,
  },
  {
    id: "ITF14",
    name: "ITF-14",
    subtitle: "Logistics & shipping barcode",
    category: "Logistics & Packaging",
    description: "Interleaved 2 of 5 standard for cartons, cases, and master shipping containers. Encodes 13 data digits plus 1 check digit.",
    defaultData: "1001234567890",
    placeholder: "Enter 13 or 14 digits (e.g. 1001234567890)",
    helper: "Enter 13 or 14 digits.",
    hasCheckDigit: true,
    supportsAutoCheckDigit: true,
    baseLength: 13,
    totalLength: 14,
    numericOnly: true,
  },
  {
    id: "codabar",
    name: "Codabar",
    subtitle: "Legacy numeric barcode",
    category: "Specialized & Archival",
    description: "Self-checking numeric standard used in libraries, blood banks, and parcel delivery services. Uses digits 0-9 and standard framing characters (A, B, C, D).",
    defaultData: "A123456789B",
    placeholder: "e.g. A123456789B",
    helper: "Enter digits with optional start/stop framing characters A, B, C, or D.",
    hasCheckDigit: false,
    supportsAutoCheckDigit: false,
    minChars: 2,
    maxChars: 30,
  },
];

export const BARCODE_PRESETS = [
  {
    id: "classic",
    name: "Classic",
    description: "Standard clean black & white with balanced proportions",
    settings: {
      lineColor: "#000000",
      background: "#FFFFFF",
      width: 2,
      height: 80,
      margin: 15,
      displayValue: true,
      textPosition: "bottom",
      fontSize: 14,
    },
  },
  {
    id: "retail",
    name: "Retail POS",
    description: "High-contrast compact layout optimized for checkout scanners",
    settings: {
      lineColor: "#000000",
      background: "#FFFFFF",
      width: 2,
      height: 65,
      margin: 12,
      displayValue: true,
      textPosition: "bottom",
      fontSize: 13,
    },
  },
  {
    id: "business",
    name: "Business & Logistics",
    description: "Tall industrial bars with generous quiet zone for distance scanning",
    settings: {
      lineColor: "#0F172A",
      background: "#FFFFFF",
      width: 2.4,
      height: 100,
      margin: 20,
      displayValue: true,
      textPosition: "bottom",
      fontSize: 15,
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Sleek modern lines with refined typography",
    settings: {
      lineColor: "#1E293B",
      background: "#FFFFFF",
      width: 1.8,
      height: 70,
      margin: 14,
      displayValue: true,
      textPosition: "bottom",
      fontSize: 13,
    },
  },
];
